import fs from 'fs';
const path = 'src/App.tsx';
const content = fs.readFileSync(path, 'utf8');

// Find the position of the last valid line we saw
const anchor = '當冷卻時間結束後，點擊上方按鈕開始全聯盟範圍的球員探索。';
const index = content.indexOf(anchor);

if (index === -1) {
    console.error('Anchor not found');
    process.exit(1);
}

const missing = [
    '                        </p>',
    '                      </div>',
    '                    ) : (',
    '                      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">',
    '                        {explorePool.map((p) => (',
    '                          <div key={p.id} className="space-y-4">',
    '                            <PlayerCard player={p} />',
    '                            <button',
    '                              onClick={() => buyPlayer(p.id)}',
    '                              className="w-full bg-blue-600 hover:bg-blue-700 text-white rounded-2xl py-4 font-black italic uppercase text-sm transition-all flex items-center justify-center gap-3 shadow-lg shadow-blue-100"',
    '                            >',
    '                              簽約球員 (${(p.price / 1000000).toFixed(1)}M)',
    '                            </button>',
    '                          </div>',
    '                        ))}',
    '                      </div>',
    '                    )}',
    '                  </div>',
    '                ) : (',
    '                  <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-8">',
    '                    {EQUIPMENT_MARKET.map((item) => (',
    '                      <div',
    '                        key={item.id}',
    '                        className="bg-white border-2 border-slate-100 rounded-3xl p-6 hover:shadow-xl transition-all relative group"',
    '                      >',
    '                        <div className="w-16 h-16 bg-slate-50 rounded-2xl flex items-center justify-center mb-6 group-hover:bg-orange-50 transition-colors">',
    '                          <item.icon',
    '                            size={32}',
    '                            className="text-slate-400 group-hover:text-orange-500"',
    '                          />',
    '                        </div>',
    '                        <div className="space-y-1 mb-6">',
    '                          <div className="text-[10px] font-black uppercase tracking-widest text-slate-400">',
    '                            {item.level} {item.type}',
    '                          </div>',
    '                          <h4 className="text-xl font-black text-slate-900 italic uppercase">',
    '                            {item.name}',
    '                          </h4>',
    '                        </div>',
    '                        <div className="flex flex-wrap gap-2 mb-8">',
    '                          {item.bonus.offense && (',
    '                            <span className="px-3 py-1 bg-blue-50 text-blue-600 rounded-lg text-[10px] font-black">',
    '                              OFF +{item.bonus.offense}',
    '                            </span>',
    '                          )}',
    '                          {item.bonus.defense && (',
    '                            <span className="px-3 py-1 bg-orange-50 text-orange-600 rounded-lg text-[10px] font-black">',
    '                              DEF +{item.bonus.defense}',
    '                            </span>',
    '                          )}',
    '                        </div>',
    '                        <button',
    '                          onClick={() => setSelectedGearPlayerId(item.id)}',
    '                          className="w-full bg-slate-900 text-white rounded-2xl py-4 font-black italic uppercase text-xs transition-all hover:bg-slate-800"',
    '                        >',
    '                          購買裝備 ($\${(item.price / 1000000).toFixed(1)}M)',
    '                        </button>',
    '                      </div>',
    '                    ))}',
    '                  </div>',
    '                )}',
    '              </div>',
    '            )}',
    '          </main>',
    '        </div>',
    '        ',
    '        <AnimatePresence>',
    '          {news && (',
    '            <motion.div',
    '              initial={{ opacity: 0, y: 50 }}',
    '              animate={{ opacity: 1, y: 0 }}',
    '              exit={{ opacity: 0, y: 50 }}',
    '              className="fixed bottom-8 left-1/2 -translate-x-1/2 z-[200]"',
    '            >',
    '              <div className="bg-slate-900 text-white px-8 py-5 rounded-[2rem] shadow-2xl flex items-center gap-6 border-2 border-white/10 backdrop-blur-xl">',
    '                <div className="w-10 h-10 bg-blue-600 rounded-2xl flex items-center justify-center animate-pulse">',
    '                  <Basketball size={20} />',
    '                </div>',
    '                <p className="font-black italic uppercase tracking-tight text-sm pr-4">',
    '                  {news}',
    '                </p>',
    '                <button',
    '                  onClick={() => setNews(null)}',
    '                  className="text-slate-500 hover:text-white transition-colors"',
    '                >',
    '                  ✕',
    '                </button>',
    '              </div>',
    '            </motion.div>',
    '          )}',
    '        </AnimatePresence>',
    '      </div>',
    '    );',
    '}'
];

const newContent = content.slice(0, index + anchor.length) + '\\n' + missing.join('\\n');
fs.writeFileSync(path, newContent);
console.log('App.tsx restored');
创新 v90建设成功建设中 v256建設成功
