import { Team, Equipment } from "./types";

export const NBA_TEAMS: Team[] = [
  {
    id: "atl",
    name: "Hawks",
    city: "Atlanta",
    abbreviation: "ATL",
    logo: "https://cdn.nba.com/logos/nba/1610612737/primary/L/logo.svg",
    color: "#E03A3E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "bos",
    name: "Celtics",
    city: "Boston",
    abbreviation: "BOS",
    logo: "https://cdn.nba.com/logos/nba/1610612738/primary/L/logo.svg",
    color: "#007A33",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "bkn",
    name: "Nets",
    city: "Brooklyn",
    abbreviation: "BKN",
    logo: "https://cdn.nba.com/logos/nba/1610612751/primary/L/logo.svg",
    color: "#000000",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "cha",
    name: "Hornets",
    city: "Charlotte",
    abbreviation: "CHA",
    logo: "https://cdn.nba.com/logos/nba/1610612766/primary/L/logo.svg",
    color: "#1D1160",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "chi",
    name: "Bulls",
    city: "Chicago",
    abbreviation: "CHI",
    logo: "https://cdn.nba.com/logos/nba/1610612741/primary/L/logo.svg",
    color: "#C8102E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "cle",
    name: "Cavaliers",
    city: "Cleveland",
    abbreviation: "CLE",
    logo: "https://cdn.nba.com/logos/nba/1610612739/primary/L/logo.svg",
    color: "#860038",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "dal",
    name: "Mavericks",
    city: "Dallas",
    abbreviation: "DAL",
    logo: "https://cdn.nba.com/logos/nba/1610612742/primary/L/logo.svg",
    color: "#00538C",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "den",
    name: "Nuggets",
    city: "Denver",
    abbreviation: "DEN",
    logo: "https://cdn.nba.com/logos/nba/1610612743/primary/L/logo.svg",
    color: "#0E2240",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "det",
    name: "Pistons",
    city: "Detroit",
    abbreviation: "DET",
    logo: "https://cdn.nba.com/logos/nba/1610612765/primary/L/logo.svg",
    color: "#C8102E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "gsw",
    name: "Warriors",
    city: "Golden State",
    abbreviation: "GSW",
    logo: "https://cdn.nba.com/logos/nba/1610612744/primary/L/logo.svg",
    color: "#1D428A",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "hou",
    name: "Rockets",
    city: "Houston",
    abbreviation: "HOU",
    logo: "https://cdn.nba.com/logos/nba/1610612745/primary/L/logo.svg",
    color: "#CE1141",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "ind",
    name: "Pacers",
    city: "Indiana",
    abbreviation: "IND",
    logo: "https://cdn.nba.com/logos/nba/1610612754/primary/L/logo.svg",
    color: "#002D62",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "lac",
    name: "Clippers",
    city: "Los Angeles",
    abbreviation: "LAC",
    logo: "https://cdn.nba.com/logos/nba/1610612746/primary/L/logo.svg",
    color: "#C8102E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "lak",
    name: "Lakers",
    city: "Los Angeles",
    abbreviation: "LAL",
    logo: "https://cdn.nba.com/logos/nba/1610612747/primary/L/logo.svg",
    color: "#552583",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "mem",
    name: "Grizzlies",
    city: "Memphis",
    abbreviation: "MEM",
    logo: "https://cdn.nba.com/logos/nba/1610612763/primary/L/logo.svg",
    color: "#5D76A9",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "mia",
    name: "Heat",
    city: "Miami",
    abbreviation: "MIA",
    logo: "https://cdn.nba.com/logos/nba/1610612748/primary/L/logo.svg",
    color: "#98002E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "mil",
    name: "Bucks",
    city: "Milwaukee",
    abbreviation: "MIL",
    logo: "https://cdn.nba.com/logos/nba/1610612749/primary/L/logo.svg",
    color: "#00471B",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "min",
    name: "Timberwolves",
    city: "Minnesota",
    abbreviation: "MIN",
    logo: "https://cdn.nba.com/logos/nba/1610612750/primary/L/logo.svg",
    color: "#0C2340",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "nop",
    name: "Pelicans",
    city: "New Orleans",
    abbreviation: "NOP",
    logo: "https://cdn.nba.com/logos/nba/1610612740/primary/L/logo.svg",
    color: "#0C2340",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "nyk",
    name: "Knicks",
    city: "New York",
    abbreviation: "NYK",
    logo: "https://cdn.nba.com/logos/nba/1610612752/primary/L/logo.svg",
    color: "#006BB6",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "okc",
    name: "Thunder",
    city: "Oklahoma City",
    abbreviation: "OKC",
    logo: "https://cdn.nba.com/logos/nba/1610612760/primary/L/logo.svg",
    color: "#007AC1",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "orl",
    name: "Magic",
    city: "Orlando",
    abbreviation: "ORL",
    logo: "https://cdn.nba.com/logos/nba/1610612753/primary/L/logo.svg",
    color: "#0077C0",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "phi",
    name: "76ers",
    city: "Philadelphia",
    abbreviation: "PHI",
    logo: "https://cdn.nba.com/logos/nba/1610612755/primary/L/logo.svg",
    color: "#006BB6",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "phx",
    name: "Suns",
    city: "Phoenix",
    abbreviation: "PHX",
    logo: "https://cdn.nba.com/logos/nba/1610612756/primary/L/logo.svg",
    color: "#1D1160",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "por",
    name: "Trail Blazers",
    city: "Portland",
    abbreviation: "POR",
    logo: "https://cdn.nba.com/logos/nba/1610612757/primary/L/logo.svg",
    color: "#E03A3E",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "sac",
    name: "Kings",
    city: "Sacramento",
    abbreviation: "SAC",
    logo: "https://cdn.nba.com/logos/nba/1610612758/primary/L/logo.svg",
    color: "#5A2D81",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "sas",
    name: "Spurs",
    city: "San Antonio",
    abbreviation: "SAS",
    logo: "https://cdn.nba.com/logos/nba/1610612759/primary/L/logo.svg",
    color: "#C4CED4",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "tor",
    name: "Raptors",
    city: "Toronto",
    abbreviation: "TOR",
    logo: "https://cdn.nba.com/logos/nba/1610612761/primary/L/logo.svg",
    color: "#CE1141",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "uta",
    name: "Jazz",
    city: "Utah",
    abbreviation: "UTA",
    logo: "https://cdn.nba.com/logos/nba/1610612762/primary/L/logo.svg",
    color: "#002B5C",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
  {
    id: "was",
    name: "Wizards",
    city: "Washington",
    abbreviation: "WAS",
    logo: "https://cdn.nba.com/logos/nba/1610612764/primary/L/logo.svg",
    color: "#002B5C",
    roster: [],
    lineup: [],
    budget: 0,
    stats: { wins: 0, losses: 0 },
  },
];

export const GET_RATING_COLOR = (ratingValue: number) => {
  if (ratingValue >= 100) return "#38BDF8"; // Sky Blue / Diamond
  if (ratingValue >= 95) return "#FFD700"; // Gold / MVP
  if (ratingValue >= 75) return "#3B82F6";
  if (ratingValue >= 65) return "#22C55E";
  return "#94A3B8";
};

export const GET_RATING_LABEL = (ratingValue: number) => {
  if (ratingValue >= 100) return "超凡入聖/神級";
  if (ratingValue >= 95) return "史詩級/MVP";
  if (ratingValue >= 85) return "全明星";
  if (ratingValue >= 75) return "優質先發";
  if (ratingValue >= 65) return "輪替陣容";
  return "邊緣球員";
};

export const CALCULATE_PLAYER_PRICE = (ratingValue: number, isLegend: boolean = false) => {
  let basePrice = 0;
  if (ratingValue >= 95) {
    basePrice = 40000000 + (ratingValue - 95) * 5000000;
    let finalPrice = basePrice * 4; // MVP 4x
    if (isLegend) finalPrice += 100000000; // Only true LEGEND gets +100M
    return finalPrice;
  }
  
  if (ratingValue >= 85) basePrice = 20000000 + (ratingValue - 85) * 2000000;
  else if (ratingValue >= 75) basePrice = 10000000 + (ratingValue - 75) * 1000000;
  else if (ratingValue >= 65) basePrice = 4000000 + (ratingValue - 65) * 500000;
  else basePrice = 1000000 + (ratingValue - 50) * 200000;
  
  return basePrice * 2; // Normal 2x
};

export const WIN_BONUS = 5000000;
export const LOSS_BONUS = 2000000;
export const EXPLORE_COOLDOWN_MS = 2 * 60 * 60 * 1000;
export const INITIAL_BUDGET = 80000000;
export const MAX_ROSTER_SIZE = 15;
export const MIN_ROSTER_SIZE = 8;
export const REGULAR_SEASON_GAMES = 30;

export const EQUIPMENT_MARKET: Equipment[] = [
  {
    id: "j-1",
    type: "JERSEY",
    name: "基礎訓練背心",
    level: "Basic",
    price: 10000000,
    bonus: { offense: 0.5 },
    icon: "Shirt",
  },
  {
    id: "j-2",
    type: "JERSEY",
    name: "標準排汗球衣",
    level: "Standard",
    price: 30000000,
    bonus: { offense: 1.0 },
    icon: "Shirt",
  },
  {
    id: "j-3",
    type: "JERSEY",
    name: "專業比賽球衣",
    level: "Pro",
    price: 80000000,
    bonus: { offense: 1.5 },
    icon: "Shirt",
  },
  {
    id: "j-4",
    type: "JERSEY",
    name: "精英加壓球衣",
    level: "Elite",
    price: 150000000,
    bonus: { offense: 2.0 },
    icon: "Shirt",
  },
  {
    id: "j-5",
    type: "JERSEY",
    name: "冠軍特仕球衣",
    level: "Master",
    price: 300000000,
    bonus: { offense: 2.5 },
    icon: "Shirt",
  },
  {
    id: "j-6",
    type: "JERSEY",
    name: "傳奇復刻球衣",
    level: "Legendary",
    price: 600000000,
    bonus: { offense: 3.0 },
    icon: "Shirt",
  },
  {
    id: "s-1",
    type: "SHORTS",
    name: "透氣網眼短褲",
    level: "Basic",
    price: 10000000,
    bonus: { defense: 0.5 },
    icon: "Square",
  },
  {
    id: "s-2",
    type: "SHORTS",
    name: "彈性運動短褲",
    level: "Standard",
    price: 30000000,
    bonus: { defense: 1.0 },
    icon: "Square",
  },
  {
    id: "s-3",
    type: "SHORTS",
    name: "專業競速短褲",
    level: "Pro",
    price: 80000000,
    bonus: { defense: 1.5 },
    icon: "Square",
  },
  {
    id: "s-4",
    type: "SHORTS",
    name: "精英防護短褲",
    level: "Elite",
    price: 150000000,
    bonus: { defense: 2.0 },
    icon: "Square",
  },
  {
    id: "s-5",
    type: "SHORTS",
    name: "全能大師短褲",
    level: "Master",
    price: 300000000,
    bonus: { defense: 2.5 },
    icon: "Square",
  },
  {
    id: "s-6",
    type: "SHORTS",
    name: "名人堂典藏短褲",
    level: "Legendary",
    price: 600000000,
    bonus: { defense: 3.0 },
    icon: "Square",
  },
  {
    id: "b-1",
    type: "SHOES",
    name: "入門籃球鞋",
    level: "Basic",
    price: 20000000,
    bonus: { offense: 0.3, defense: 0.2 },
    icon: "Footprints",
  },
  {
    id: "b-2",
    type: "SHOES",
    name: "校隊款戰靴",
    level: "Standard",
    price: 50000000,
    bonus: { offense: 0.6, defense: 0.4 },
    icon: "Footprints",
  },
  {
    id: "b-3",
    type: "SHOES",
    name: "職業選用戰靴",
    level: "Pro",
    price: 120000000,
    bonus: { offense: 0.9, defense: 0.6 },
    icon: "Footprints",
  },
  {
    id: "b-4",
    type: "SHOES",
    name: "簽名款精英鞋",
    level: "Elite",
    price: 250000000,
    bonus: { offense: 1.2, defense: 0.8 },
    icon: "Footprints",
  },
  {
    id: "b-5",
    type: "SHOES",
    name: "總決賽限量款",
    level: "Master",
    price: 450000000,
    bonus: { offense: 1.5, defense: 1.0 },
    icon: "Footprints",
  },
  {
    id: "b-6",
    type: "SHOES",
    name: "MVP 傳奇金靴",
    level: "Legendary",
    price: 800000000,
    bonus: { offense: 1.8, defense: 1.2 },
    icon: "Footprints",
  },
  {
    id: "k-1",
    type: "KNEE_PADS",
    name: "簡易護膝",
    level: "Basic",
    price: 8000000,
    bonus: { defense: 0.5 },
    icon: "Shield",
  },
  {
    id: "k-2",
    type: "KNEE_PADS",
    name: "海綿防撞護膝",
    level: "Standard",
    price: 24000000,
    bonus: { defense: 1.0 },
    icon: "Shield",
  },
  {
    id: "k-3",
    type: "KNEE_PADS",
    name: "蜂巢減震護膝",
    level: "Pro",
    price: 65000000,
    bonus: { defense: 1.5 },
    icon: "Shield",
  },
  {
    id: "k-4",
    type: "KNEE_PADS",
    name: "碳纖維支撐護膝",
    level: "Elite",
    price: 120000000,
    bonus: { defense: 2.0 },
    icon: "Shield",
  },
  {
    id: "k-5",
    type: "KNEE_PADS",
    name: "航太太空材護膝",
    level: "Master",
    price: 250000000,
    bonus: { defense: 2.5 },
    icon: "Shield",
  },
  {
    id: "k-6",
    type: "KNEE_PADS",
    name: "絕對領域護膝",
    level: "Legendary",
    price: 500000000,
    bonus: { defense: 3.0 },
    icon: "Shield",
  },
  {
    id: "w-1",
    type: "WRISTBAND",
    name: "吸汗護腕",
    level: "Basic",
    price: 5000000,
    bonus: { offense: 0.5 },
    icon: "Watch",
  },
  {
    id: "w-2",
    type: "WRISTBAND",
    name: "排和導流護腕",
    level: "Standard",
    price: 15000000,
    bonus: { offense: 1.0 },
    icon: "Watch",
  },
  {
    id: "w-3",
    type: "WRISTBAND",
    name: "加壓保護護腕",
    level: "Pro",
    price: 45000000,
    bonus: { offense: 1.5 },
    icon: "Watch",
  },
  {
    id: "w-4",
    type: "WRISTBAND",
    name: "感知纖維護腕",
    level: "Elite",
    price: 100000000,
    bonus: { offense: 2.0 },
    icon: "Watch",
  },
  {
    id: "w-5",
    type: "WRISTBAND",
    name: "精準投射護腕",
    level: "Master",
    price: 200000000,
    bonus: { offense: 2.5 },
    icon: "Watch",
  },
  {
    id: "w-6",
    type: "WRISTBAND",
    name: "全明星榮耀護腕",
    level: "Legendary",
    price: 400000000,
    bonus: { offense: 3.0 },
    icon: "Watch",
  },
  {
    id: "h-1",
    type: "HEADBAND",
    name: "基礎運動頭巾",
    level: "Basic",
    price: 6000000,
    bonus: { offense: 0.25, defense: 0.25 },
    icon: "Zap",
  },
  {
    id: "h-2",
    type: "HEADBAND",
    name: "酷涼降溫頭巾",
    level: "Standard",
    price: 18000000,
    bonus: { offense: 0.5, defense: 0.5 },
    icon: "Zap",
  },
  {
    id: "h-3",
    type: "HEADBAND",
    name: "戰術分析頭巾",
    level: "Pro",
    price: 50000000,
    bonus: { offense: 0.75, defense: 0.75 },
    icon: "Zap",
  },
  {
    id: "h-4",
    type: "HEADBAND",
    name: "精英格紋頭巾",
    level: "Elite",
    price: 110000000,
    bonus: { offense: 1.0, defense: 1.0 },
    icon: "Zap",
  },
  {
    id: "h-5",
    type: "HEADBAND",
    name: "大師絲綢頭巾",
    level: "Master",
    price: 220000000,
    bonus: { offense: 1.25, defense: 1.25 },
    icon: "Zap",
  },
  {
    id: "h-6",
    type: "HEADBAND",
    name: "傳奇王朝頭巾",
    level: "Legendary",
    price: 450000000,
    bonus: { offense: 1.5, defense: 1.5 },
    icon: "Zap",
  },
];
